### ISSUE TITLE
Projects not running

### ISSUE THREAD

**Issue by samarmir** [damienbod/AngularLocalizationAspNetCore#11]
I'm simply not able to get the projects to run in vs17. 

- angular localization with an asp.net core mvc service
- creating and requesting sql localized data in asp.net core

Having installed all nuget and npm packages and webpack dev server, configured the database connecting string, when running the project I just get a Loading text message?

**Comment by damienbod** [comment]
Hi @samarmir you need to build the Angular appication. You can check using F12 in the browser

Try from the cmd:
> dotnet restore
> npm install
> npm run build-dev

It should then work, otherwisr you're missing some required tools like nodejs of sass. If this works, try installing the npm task runner in VS.

Greetings Damien

**Comment by samarmir** [comment]
Hi Damien 
I got it working, thanks for your help. 
I had to do a: npm rebuild node-sass --force
